### ISSUE TITLE
Definir intenções que vamos abordar e as queries do jinkanpy

### ISSUE THREAD

**Issue by dudaholandah** [seraphritt/PAA-projeto-disciplina#11]
- [x] quem é o personagem _  ?
- [x]  sobre o que é o anime _  ?
- [x] qual o gênero do anime _ ?
- [x] me recomende um anime.
- [x] me fale um anime da temporada
- [x] qual o anime top _ ?

**Comment by seraphritt** [comment]
Pro protótipo acho que vale a gente responder as 2 primeiras perguntas.
O resto dá pra implementar também, tem um rank na api e tem as notas de cada anime também.
